# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellout < Formula
  desc "Turn one English sentence into one shell command, confirm, run."
  homepage "https://github.com/JakubMajcher/shellout"
  version "0.1-beta"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JakubMajcher/shellout/releases/download/v0.1-beta/shellout_0.1-beta_darwin_amd64.tar.gz"
      sha256 "cd5d5fc0594efd34d82160026151dab61d81c9585d35b19c7d7ee41f8b4422b1"

      define_method(:install) do
        bin.install "shellout"
        bin.install_symlink "shellout" => "sho"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JakubMajcher/shellout/releases/download/v0.1-beta/shellout_0.1-beta_darwin_arm64.tar.gz"
      sha256 "3e9194a8bb5137b2cf4d9dee568d02419ee2b7e84bfa6932169d5365435b9054"

      define_method(:install) do
        bin.install "shellout"
        bin.install_symlink "shellout" => "sho"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JakubMajcher/shellout/releases/download/v0.1-beta/shellout_0.1-beta_linux_amd64.tar.gz"
      sha256 "80e5852790d05bcb211e68e0512321d3dc890dc91e5657607b43c42bdf72c2eb"
      define_method(:install) do
        bin.install "shellout"
        bin.install_symlink "shellout" => "sho"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JakubMajcher/shellout/releases/download/v0.1-beta/shellout_0.1-beta_linux_arm64.tar.gz"
      sha256 "930acae23e03dc906ad808bef79ef66730bf1fdaa4e9c18c89a6189446bf401b"
      define_method(:install) do
        bin.install "shellout"
        bin.install_symlink "shellout" => "sho"
      end
    end
  end

  test do
    system "#{bin}/shellout", "--version"
  end
end
