# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellout < Formula
  desc "Turn one English sentence into one shell command, confirm, run."
  homepage "https://github.com/JakubMajcher/shellout"
  version "0.1-beta"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JakubMajcher/shellout/releases/download/0.1-beta/shellout_0.1-beta_darwin_amd64.tar.gz"
      sha256 "c2e86e9ffbb7e42730e842a5e635e2bf8e540147955a1bcfffe7c6dfb1290c73"

      define_method(:install) do
        bin.install "shellout"
        bin.install_symlink "shellout" => "sho"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JakubMajcher/shellout/releases/download/0.1-beta/shellout_0.1-beta_darwin_arm64.tar.gz"
      sha256 "f34455f160c8d6b2ba56d5463fad6f96ec15934702f0400e8a0359dd772b1006"

      define_method(:install) do
        bin.install "shellout"
        bin.install_symlink "shellout" => "sho"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JakubMajcher/shellout/releases/download/0.1-beta/shellout_0.1-beta_linux_amd64.tar.gz"
      sha256 "aa7b05f4d3242b4b4b745c7baa3f10232a053ce8a7e23b96840f17be9fae87ca"
      define_method(:install) do
        bin.install "shellout"
        bin.install_symlink "shellout" => "sho"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JakubMajcher/shellout/releases/download/0.1-beta/shellout_0.1-beta_linux_arm64.tar.gz"
      sha256 "a32120abd8ad2a9e12a77ac0517a1f67f7c65d827573237e9b8d77f657c53989"
      define_method(:install) do
        bin.install "shellout"
        bin.install_symlink "shellout" => "sho"
      end
    end
  end

  test do
    system "#{bin}/shellout", "--version"
  end
end
